import { useState, useEffect } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
// import { api } from "../lib/api";
import { ProductGrid } from "../components/demo/ProductGrid";
import { toast } from "sonner";
import { DashboardLayout } from '@/components/layout/DashboardLayout';  

// Sample hardcoded products (replace with API fetch)
const sampleProducts = [
	{
        id: "1", 
        title: "Wireless Headphones",
        price: 99.99, 
        imageUrl: "https://example.com/headphones.jpg",
        tags: ["wireless", "audio"],
        productType: "Electronics",
        vendor: "TechVendor",
        inStock: true,
	},
	{
		id: "2",
		title: "Smartphone Case",
		price: 19.99,
		imageUrl: "https://example.com/case.jpg",
		tags: ["phone", "protection"],
		productType: "Accessories",
		vendor: "TechVendor",
		inStock: true,
	},
	{
		id: "3",
		title: "Laptop Stand",
		price: 49.99,
		imageUrl: "https://example.com/stand.jpg",
		tags: ["laptop", "ergonomic"],
		productType: "Accessories",
		vendor: "TechVendor",
		inStock: true,
	},
    {
        id: "4",
        title: "Bluetooth Speaker",
        price: 79.99,
        imageUrl: "https://example.com/speaker.jpg",
        tags: ["audio", "portable", "bluetooth"],
        productType: "Electronics",
        vendor: "SoundWave",
        inStock: true,
    },
    {
        id: "5",
        title: "Mechanical Keyboard",
        price: 129.99,
        imageUrl: "https://example.com/keyboard.jpg",
        tags: ["keyboard", "mechanical", "gaming"],
        productType: "Electronics",
        vendor: "KeyPro",
        inStock: false,
    },
    {
        id: "6",
        title: "Wireless Mouse",
        price: 39.99,
        imageUrl: "https://example.com/mouse.jpg",
        tags: ["mouse", "wireless", "ergonomic"],
        productType: "Accessories",
        vendor: "KeyPro",
        inStock: true,
    },
    {
        id: "7",
        title: "USB-C Charging Cable",
        price: 14.99,
        imageUrl: "https://example.com/cable.jpg",
        tags: ["charging", "usb-c"],
        productType: "Accessories",
        vendor: "ChargeIt",
        inStock: true,
    },
    {
        id: "8",
        title: "Smartwatch",
        price: 199.99,
        imageUrl: "https://example.com/smartwatch.jpg",
        tags: ["wearable", "fitness", "smart"],
        productType: "Electronics",
        vendor: "FitTech",
        inStock: true,
    },
    {
        id: "9",
        title: "Noise Cancelling Earbuds",
        price: 149.99,
        imageUrl: "https://example.com/earbuds.jpg",
        tags: ["audio", "wireless", "noise-cancelling"],
        productType: "Electronics",
        vendor: "SoundWave",
        inStock: false,
    },
    {
        id: "10",
        title: "Webcam 1080p",
        price: 59.99,
        imageUrl: "https://example.com/webcam.jpg",
        tags: ["camera", "streaming", "remote-work"],
        productType: "Electronics",
        vendor: "VisionTech",
        inStock: true,
    },
    {
        id: "11",
        title: "Reusable Water Bottle",
        price: 24.99,
        imageUrl: "https://example.com/waterbottle.jpg",
        tags: ["eco-friendly", "hydration"],
        productType: "Lifestyle",
        vendor: "GreenLife",
        inStock: true,
    },
    {
        id: "12",
        title: "Aromatic Soy Candle",
        price: 18.50,
        imageUrl: "https://example.com/candle.jpg",
        tags: ["home", "relaxation", "scented"],
        productType: "Home",
        vendor: "CozyCorner",
        inStock: true,
    },
    {
        id: "13",
        title: "Minimalist Backpack",
        price: 89.99,
        imageUrl: "https://example.com/backpack.jpg",
        tags: ["travel", "fashion", "storage"],
        productType: "Fashion",
        vendor: "UrbanCarry",
        inStock: false,
    },
    {
        id: "14",
        title: "Desk Plant (Succulent)",
        price: 15.99,
        imageUrl: "https://example.com/succulent.jpg",
        tags: ["plant", "decor", "workspace"],
        productType: "Home",
        vendor: "Plantify",
        inStock: true,
    },
    {
        id: "15",
        title: "Instant Ramen Variety Pack",
        price: 29.99,
        imageUrl: "https://example.com/ramen.jpg",
        tags: ["food", "convenience", "snacks"],
        productType: "Grocery",
        vendor: "NoodleHouse",
        inStock: true,
    },
    {
        id: "16",
        title: "Yoga Mat",
        price: 44.99,
        imageUrl: "https://example.com/yogamat.jpg",
        tags: ["fitness", "wellness", "exercise"],
        productType: "Fitness",
        vendor: "ZenMotion",
        inStock: true,
    },
    {
        id: "17",
        title: "Board Game: City Builders",
        price: 54.99,
        imageUrl: "https://example.com/boardgame.jpg",
        tags: ["games", "strategy", "multiplayer"],
        productType: "Entertainment",
        vendor: "PlayForge",
        inStock: true,
    },
    {
        id: "18",
        title: "Vintage-Style Wall Clock",
        price: 67.00,
        imageUrl: "https://example.com/clock.jpg",
        tags: ["decor", "timepiece", "vintage"],
        productType: "Home",
        vendor: "TimelessCo",
        inStock: false,
    },
    {
        id: "19",
        title: "Cookbook: 30-Minute Meals",
        price: 34.95,
        imageUrl: "https://example.com/cookbook.jpg",
        tags: ["cooking", "recipes", "healthy"],
        productType: "Books",
        vendor: "KitchenReads",
        inStock: true,
    },
    {
        id: "20",
        title: "Noise-Reducing Sleep Mask",
        price: 22.99,
        imageUrl: "https://example.com/sleepmask.jpg",
        tags: ["sleep", "wellness", "travel"],
        productType: "Wellness",
        vendor: "RestEasy",
        inStock: true,
    },
    {
        id: "1", 
        title: "Wireless Headphones",
        price: 99.99, 
        imageUrl: "https://example.com/headphones.jpg",
        tags: ["wireless", "audio"],
        productType: "Electronics",
        vendor: "TechVendor",
        inStock: true,
	},
	{
		id: "2",
		title: "Smartphone Case",
		price: 19.99,
		imageUrl: "https://example.com/case.jpg",
		tags: ["phone", "protection"],
		productType: "Accessories",
		vendor: "TechVendor",
		inStock: true,
	},
	{
		id: "3",
		title: "Laptop Stand",
		price: 49.99,
		imageUrl: "https://example.com/stand.jpg",
		tags: ["laptop", "ergonomic"],
		productType: "Accessories",
		vendor: "TechVendor",
		inStock: true,
	},
    {
        id: "4",
        title: "Bluetooth Speaker",
        price: 79.99,
        imageUrl: "https://example.com/speaker.jpg",
        tags: ["audio", "portable", "bluetooth"],
        productType: "Electronics",
        vendor: "SoundWave",
        inStock: true,
    },
    {
        id: "5",
        title: "Mechanical Keyboard",
        price: 129.99,
        imageUrl: "https://example.com/keyboard.jpg",
        tags: ["keyboard", "mechanical", "gaming"],
        productType: "Electronics",
        vendor: "KeyPro",
        inStock: false,
    },
    {
        id: "6",
        title: "Wireless Mouse",
        price: 39.99,
        imageUrl: "https://example.com/mouse.jpg",
        tags: ["mouse", "wireless", "ergonomic"],
        productType: "Accessories",
        vendor: "KeyPro",
        inStock: true,
    },
    {
        id: "7",
        title: "USB-C Charging Cable",
        price: 14.99,
        imageUrl: "https://example.com/cable.jpg",
        tags: ["charging", "usb-c"],
        productType: "Accessories",
        vendor: "ChargeIt",
        inStock: true,
    },
    {
        id: "8",
        title: "Smartwatch",
        price: 199.99,
        imageUrl: "https://example.com/smartwatch.jpg",
        tags: ["wearable", "fitness", "smart"],
        productType: "Electronics",
        vendor: "FitTech",
        inStock: true,
    },
    {
        id: "9",
        title: "Noise Cancelling Earbuds",
        price: 149.99,
        imageUrl: "https://example.com/earbuds.jpg",
        tags: ["audio", "wireless", "noise-cancelling"],
        productType: "Electronics",
        vendor: "SoundWave",
        inStock: false,
    },
    {
        id: "10",
        title: "Webcam 1080p",
        price: 59.99,
        imageUrl: "https://example.com/webcam.jpg",
        tags: ["camera", "streaming", "remote-work"],
        productType: "Electronics",
        vendor: "VisionTech",
        inStock: true,
    },
    {
        id: "11",
        title: "Reusable Water Bottle",
        price: 24.99,
        imageUrl: "https://example.com/waterbottle.jpg",
        tags: ["eco-friendly", "hydration"],
        productType: "Lifestyle",
        vendor: "GreenLife",
        inStock: true,
    },
    {
        id: "12",
        title: "Aromatic Soy Candle",
        price: 18.50,
        imageUrl: "https://example.com/candle.jpg",
        tags: ["home", "relaxation", "scented"],
        productType: "Home",
        vendor: "CozyCorner",
        inStock: true,
    },
    {
        id: "13",
        title: "Minimalist Backpack",
        price: 89.99,
        imageUrl: "https://example.com/backpack.jpg",
        tags: ["travel", "fashion", "storage"],
        productType: "Fashion",
        vendor: "UrbanCarry",
        inStock: false,
    },
    {
        id: "14",
        title: "Desk Plant (Succulent)",
        price: 15.99,
        imageUrl: "https://example.com/succulent.jpg",
        tags: ["plant", "decor", "workspace"],
        productType: "Home",
        vendor: "Plantify",
        inStock: true,
    },
    {
        id: "15",
        title: "Instant Ramen Variety Pack",
        price: 29.99,
        imageUrl: "https://example.com/ramen.jpg",
        tags: ["food", "convenience", "snacks"],
        productType: "Grocery",
        vendor: "NoodleHouse",
        inStock: true,
    },
    {
        id: "16",
        title: "Yoga Mat",
        price: 44.99,
        imageUrl: "https://example.com/yogamat.jpg",
        tags: ["fitness", "wellness", "exercise"],
        productType: "Fitness",
        vendor: "ZenMotion",
        inStock: true,
    },
    {
        id: "17",
        title: "Board Game: City Builders",
        price: 54.99,
        imageUrl: "https://example.com/boardgame.jpg",
        tags: ["games", "strategy", "multiplayer"],
        productType: "Entertainment",
        vendor: "PlayForge",
        inStock: true,
    },
    {
        id: "18",
        title: "Vintage-Style Wall Clock",
        price: 67.00,
        imageUrl: "https://example.com/clock.jpg",
        tags: ["decor", "timepiece", "vintage"],
        productType: "Home",
        vendor: "TimelessCo",
        inStock: false,
    },
    {
        id: "19",
        title: "Cookbook: 30-Minute Meals",
        price: 34.95,
        imageUrl: "https://example.com/cookbook.jpg",
        tags: ["cooking", "recipes", "healthy"],
        productType: "Books",
        vendor: "KitchenReads",
        inStock: true,
    },
    {
        id: "20",
        title: "Noise-Reducing Sleep Mask",
        price: 22.99,
        imageUrl: "https://example.com/sleepmask.jpg",
        tags: ["sleep", "wellness", "travel"],
        productType: "Wellness",
        vendor: "RestEasy",
        inStock: true,
    },
];

export default function WebStore() {
	const [sessionId] = useState(() => `session_${Date.now()}_${Math.random()}`);

	return (
        <DashboardLayout> 
            <div className="max-w-7xl mx-auto p-6">
                <div className="mb-8">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">
                        Welcome to Our Store!
                    </h1>
                </div>

                <ProductGrid products={sampleProducts} />
            </div>
        </DashboardLayout> 
	);
}
